### ISSUE TITLE
Document detection improvement

### ISSUE THREAD

**Issue by zedtux** [Michaelvilleneuve/react-native-document-scanner#40]
Hello @Michaelvilleneuve,

First of all, thank you so much for this great library, I'm still missing the Android version, but for iOS, that's rocks.

While all is working fine, now that we're using it in production, we are starting to see the detection limitations.

Is there a way to improve the sheet detection ?

Thank you

**Comment by Michaelvilleneuve** [comment]
Hi ! Thank you, happy to know that people are successfully using it in production 👍 

When you say limitation do you mean that rectangle are not accurate, or the lib does not detect them at all ?

For now there are not many options that would allow to tweak the recognition. 
However, detection is pretty basic, if you take a look at IPDFCameraViewController file, you will found these two methods : 

```objc
- (IPDFRectangeType) typeForRectangle: (CIRectangleFeature*) rectangle {
    if (fabs(rectangle.topRight.y - rectangle.topLeft.y) > 100 ||
        fabs(rectangle.topRight.x - rectangle.bottomRight.x) > 100 ||
        fabs(rectangle.topLeft.x - rectangle.bottomLeft.x) > 100 ||
        fabs(rectangle.bottomLeft.y - rectangle.bottomRight.y) > 100) {
        return IPDFRectangeTypeBadAngle;
    } else if ((_glkView.frame.origin.y + _glkView.frame.size.height) - rectangle.topLeft.y > 150 ||
               (_glkView.frame.origin.y + _glkView.frame.size.height) - rectangle.topRight.y > 150 ||
               _glkView.frame.origin.y - rectangle.bottomLeft.y > 150 ||
               _glkView.frame.origin.y - rectangle.bottomRight.y > 150) {
        return IPDFRectangeTypeTooFar;
    }
    return IPDFRectangeTypeGood;
}

BOOL rectangleDetectionConfidenceHighEnough(float confidence)
{
    return (confidence > 1.0);
}
```

They decide wether the detected rectangle seem correct or not. 
You can easily tweak them in order to avoid detection of incorrect rectangles.

For the rectangle detection itself, take a look at these two methods : 

```objc
- (CIDetector *)rectangleDetetor
{
    static CIDetector *detector = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^
    {
          detector = [CIDetector detectorOfType:CIDetectorTypeRectangle context:nil options:@{CIDetectorAccuracy : CIDetectorAccuracyLow,CIDetectorTracking : @(YES)}];
    });
    return detector;
}

- (CIDetector *)highAccuracyRectangleDetector
{
    static CIDetector *detector = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^
    {
        detector = [CIDetector detectorOfType:CIDetectorTypeRectangle context:nil options:@{CIDetectorAccuracy : CIDetectorAccuracyHigh, CIDetectorReturnSubFeatures: @(YES) }];
    });
    return detector;
}
```

There are many ways to improve detection but what I ended up doing for my project was to create a another library that would allow the user to adjust the detected area. 

![GIF](https://camo.githubusercontent.com/0ac887deaa7263172a5fd2759dba3d692e98585a/68747470733a2f2f73332d65752d776573742d312e616d617a6f6e6177732e636f6d2f6d69636861656c76696c6c656e657576652f64656d6f2d63726f702e676966)

See : https://github.com/Michaelvilleneuve/react-native-perspective-image-cropper

So far users have been happy with the result, but my need might not be similar to yours.

**Comment by zedtux** [comment]
> When you say limitation do you mean that rectangles are not accurate, or the lib does not detect them at all ?

I meant that rectangles are not accurate.

The 2 cases I have in mind, where the rectangle detection is not accurate are :

 - A coloured sheet on a white table, with many source lights, projecting many shadows of different intensities : The rectangles seemed to match the shadows
 - A magazine on a glass table : The rectangles was matching some forms of the magazine

In my tests, of white sheet papers on a wood table, detection was perfect so it's really about tweaking detection.

**Comment by Michaelvilleneuve** [comment]
Have you tried to change the `contrast` and `saturation` prop ?
