### ISSUE TITLE
The screen with scanner freezes and app crashes

### ISSUE THREAD

**Issue by vosamoilenko** [Michaelvilleneuve/react-native-document-scanner#5]
I found a problem with crashing an app while the scanner is working. I cannot detect the problem when it crashes. If this happens, 90% the screen is black, I mean, when the phone just lies on the table.

**Comment by Michaelvilleneuve** [comment]
Is your iPhone plugged to your mac and xcode while scanning ? I've had crashes while plugged but none when compile in release on the iPhone

**Comment by vosamoilenko** [comment]
I have already done test Flight and it's crashed again

**Comment by Michaelvilleneuve** [comment]
Ok, try to provide more info if you manage to reproduce it :)

**Comment by Michaelvilleneuve** [comment]
@vosamoilenko you seemed to want it, here it is https://github.com/Michaelvilleneuve/react-native-custom-crop, to not hesitate to give me your feedback :)

**Comment by guilherme-dias** [comment]
I'm facing this issue. Seems like sometimes the component doesn't render correctly and freezes the app. I'm running in release on my iPhone 5s that is used for tests. It does not happens everytime, but it might occur frequently.

I need to rerender the scanner for scanning multiple documents, since the props option bugs after some tries, it captures the photo right after the component renders.

I think i just need to manage why its freezing, the props option its not really necessary. Have someone solved this? Thanks.
